version: "2"
services:
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    mem_limit: 20m

  web:
   build: ./app
   links:
      - db
   ports:
      - "5000:5000"
   mem_limit: 20m
   logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  fluentd:
   build: ./fluentd
   volumes:
      - ./fluentd/conf:/fluentd/etc
   ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elastic/elasticsearch:6.4.3
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: elastic/kibana:6.4.3
    ports:
      - "5601:5601"
  
